# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 19:56
from __future__ import unicode_literals

import croppy.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_ensure_last_login_is_nullable'),
    ]

    operations = [
#        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.AddField(
                model_name='membership',
                name='crops',
                field=croppy.fields.CropField(default=dict, editable=False, image_field=b'avatar'),
            ),
#        ]),
    ]
