# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170410_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='committees',
            field=models.ManyToManyField(blank=True, related_name='memberships', to='committees.Committee', verbose_name='committees'),
        ),
        migrations.AlterField(
            model_name='user',
            name='accounts',
            field=models.ManyToManyField(related_name='users', through='profiles.Membership', to='accounts.Account', verbose_name='accounts'),
        ),
    ]
