# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 13:22
from __future__ import unicode_literals

import common.storage_backends
import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170415_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='avatar',
            field=models.ImageField(blank=True, storage=common.storage_backends.StableS3BotoStorage(file_overwrite=False), upload_to=common.utils.avatar_upload_to),
        ),
    ]
