# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 08:52
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170415_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(),
        ),
    ]
