# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170524_0352'),
        ('profiles', '0006_auto_20170518_0822'),
    ]

    operations = [
    ]
