# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170524_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_notifications_read',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
