# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 11:00
from __future__ import unicode_literals

from django.db import migrations, models


def update_role(apps, schema_editor):
    Membership = apps.get_model("profiles", "Membership")
    rows_role_in_zero = Membership.objects.filter(role=0)
    for row in rows_role_in_zero:
        row.role = 1  # Board Chair
        row.is_admin = True
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20170615_0445'),
    ]

    operations = [
        migrations.RunPython(update_role),
    ]
