# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_update_role_for_old_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Board Member'), (21, 'Executive Director'), (20, 'CEO'), (1, 'Board Chair'), (6, 'Staff'), (4, 'Guest'), (5, 'Vendor'), (7, 'Consultant'), (3, 'Executive Assistant')], default=2, verbose_name='role'),
        ),
    ]
