# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_user_date_notifications_read'),
        ('profiles', '0009_auto_20170619_1053'),
    ]

    operations = [
    ]
