# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_merge_20170605_0626'),
        ('profiles', '0010_merge_20170620_0707'),
    ]

    operations = [
    ]
