# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 16:26
from __future__ import unicode_literals

import common.utils
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_merge_20170627_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='avatar',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url=b'/media/avatars/', location=b'/home/ssharkey/lanshark82@gmail.com/devel/clients/boarddirector/src/public/media/avatars'), upload_to=common.utils.avatar_upload_to),
        ),
    ]
