# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 05:00
from __future__ import unicode_literals

import common.utils
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20170705_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='membership',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='membership',
            name='title',
            field=models.CharField(blank=True, max_length=225, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='avatar',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url=b'/media/avatars/', location=b'/home/ubuntu/www/boarddirector/public/media/avatars'), upload_to=common.utils.avatar_upload_to),
        ),
    ]
