# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 11:53
from __future__ import unicode_literals

import common.utils
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20170910_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='custom_role_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='custom role name'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='avatar',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url=b'/media/avatars/', location=b'/home/lhs/boarddirector/public/media/avatars'), upload_to=common.utils.avatar_upload_to),
        ),
    ]
