# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 09:54
from __future__ import unicode_literals

import common.utils
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20171128_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='work_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='membership',
            name='work_city',
            field=models.CharField(blank=True, max_length=50, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='membership',
            name='work_country',
            field=models.CharField(blank=True, max_length=50, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='membership',
            name='work_secondary_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='secondary address'),
        ),
        migrations.AddField(
            model_name='membership',
            name='work_state',
            field=models.CharField(blank=True, max_length=50, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='membership',
            name='work_zip',
            field=models.CharField(blank=True, max_length=50, verbose_name='zip'),
        ),
    ]
