# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 14:07
from __future__ import unicode_literals

import common.utils
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20171214_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bosses', to='profiles.Membership'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='avatar',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url=b'/media/avatars/', location=b'/home/dima/Projects/upwork/17-boarddirector/bdco/public/media/avatars'), upload_to=common.utils.avatar_upload_to),
        ),
    ]
