# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 09:19
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('url', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('total_storage', models.BigIntegerField(default=0, verbose_name='total storage')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('date_cancel', models.DateTimeField(blank=True, null=True, verbose_name='cancellation date')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('unlimited_trial', models.BooleanField(default=False, verbose_name='unlimited trial')),
                ('logo', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=b'logotypes/%Y%m%d', verbose_name='logotype')),
                ('send_notification', models.BooleanField(default=True, verbose_name='send automatic email notifications')),
                ('view_email', models.BooleanField(default=True, verbose_name='view email')),
                ('show_guide', models.BooleanField(default=True, verbose_name='getting started')),
            ],
        ),
    ]
