# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_date_trial_ends'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='default_meetings_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_trial_ends',
            field=models.DateTimeField(blank=True, help_text=b'if this date is not set, then trial period ends 21 days after account creation date', null=True, verbose_name='trial end date'),
        ),
    ]
