# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 09:19
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_account_plan'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('file', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=b'uploads/news/%Y%m%d', verbose_name='image')),
                ('is_publish', models.BooleanField(default=True, verbose_name='published')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account', verbose_name='account')),
                ('created_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Membership', verbose_name='member')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
