# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 09:19
from __future__ import unicode_literals

import billing.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, null=True, verbose_name='credit card number')),
                ('expiration_month', models.PositiveSmallIntegerField(null=True, verbose_name='expiration month')),
                ('expiration_year', models.PositiveSmallIntegerField(null=True, verbose_name='expiration year')),
                ('cvv', models.CharField(max_length=4, null=True, verbose_name='cvv')),
                ('cycle', models.PositiveIntegerField(choices=[(1, 'every month'), (2, 'every year')], default=2, verbose_name='billing cycle')),
                ('address', models.CharField(max_length=250, verbose_name='billing address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(max_length=100, verbose_name='province/state')),
                ('zip', models.PositiveIntegerField(null=True, verbose_name='zip')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('mail', models.EmailField(max_length=254, verbose_name='billing mail')),
                ('name', models.CharField(max_length=255, verbose_name='billing name')),
                ('discount', models.CharField(blank=True, max_length=20, verbose_name='discount code')),
                ('unit_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='unit number')),
                ('last4', models.CharField(blank=True, max_length=4, null=True, verbose_name='last4')),
                ('card_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='card type')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_settings', to='accounts.Account', verbose_name='account')),
            ],
            options={
                'verbose_name_plural': 'Billing Settings objects',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.PositiveIntegerField(verbose_name='payment')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='payment date')),
                ('status', models.PositiveIntegerField(choices=[(1, 'paid'), (2, 'pending'), (3, 'failed')], default=2, verbose_name='status')),
                ('payed_period_end', models.DateTimeField(verbose_name='payed period end')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.Account', verbose_name='account')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField(choices=[(1, 'Starter (Introduction Offer)'), (2, 'Standard (Introduction Offer)'), (3, 'Premier (Introduction Offer)'), (4, 'Starter'), (5, 'Standard'), (6, 'Premier')], default=2, unique=True, verbose_name='name')),
                ('max_members', models.PositiveIntegerField(verbose_name='max number of members')),
                ('max_storage', billing.fields.BigIntegerSizeField(help_text='In GB.', verbose_name='max storage size')),
                ('month_price', models.PositiveIntegerField(verbose_name='price per month')),
                ('year_price', models.PositiveIntegerField(verbose_name='price per year')),
                ('stripe_month_plan_id', models.CharField(max_length=70, verbose_name='Stripe Monthly Plan ID')),
                ('stripe_year_plan_id', models.CharField(max_length=70, verbose_name='Stripe Yearly Plan ID')),
                ('available', models.BooleanField(default=False, verbose_name='Available')),
            ],
            options={
                'ordering': ['month_price'],
            },
        ),
    ]
