# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20180411_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='pname',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True, verbose_name='plan name'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.PositiveIntegerField(choices=[(1, 'Starter (Introduction Offer)'), (2, 'Standard (Introduction Offer)'), (3, 'Premier (Introduction Offer)'), (4, 'Starter'), (5, 'Standard'), (6, 'Premier')], default=2, editable=False, verbose_name='name type'),
        ),
    ]
