# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_account_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('summary', models.CharField(blank=True, max_length=250, verbose_name='short summary')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='accounts.Account', verbose_name='account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
