# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 20:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 9, 20, 9, 31, 83577, tzinfo=utc), verbose_name='upload date'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 9, 20, 9, 31, 83577, tzinfo=utc), verbose_name='upload date'),
        ),
    ]
