# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20170409_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='upload date'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='upload date'),
        ),
    ]
