# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 13:22
from __future__ import unicode_literals

import common.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20170410_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='file',
            field=models.FileField(storage=common.storage_backends.StableS3BotoStorage(acl=b'private', file_overwrite=False), upload_to=b'uploads/docs/%Y%m%d', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='pdf_preview',
            field=models.FileField(blank=True, null=True, storage=common.storage_backends.StableS3BotoStorage(acl=b'private', file_overwrite=False), upload_to=b'uploads/docs/%Y%m%d', verbose_name='pdf_preview'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=common.storage_backends.StableS3BotoStorage(acl=b'private', file_overwrite=False), upload_to=b'uploads/docs/%Y%m%d', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf_preview',
            field=models.FileField(blank=True, null=True, storage=common.storage_backends.StableS3BotoStorage(acl=b'private', file_overwrite=False), upload_to=b'uploads/docs/%Y%m%d', verbose_name='pdf_preview'),
        ),
    ]
