# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 09:45
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20170518_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to=b'uploads/docs/%Y%m%d', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='pdf_preview',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=b'uploads/docs/%Y%m%d', verbose_name='pdf_preview'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to=b'uploads/docs/%Y%m%d', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf_preview',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=b'uploads/docs/%Y%m%d', verbose_name='pdf_preview'),
        ),
    ]
