# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20170618_2154'),
        ('documents', '0005_auto_20170615_0445'),
    ]

    operations = [
    ]
