# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-15 20:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20170615_0445'),
        ('documents', '0006_merge_20170629_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_page', models.PositiveIntegerField()),
                ('type', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('geometry_tools_version', models.PositiveSmallIntegerField()),
                ('geometry_json', jsonfield.fields.JSONField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='accounts.Account')),
                ('audit_trail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='documents.AuditTrail')),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='documents.Document')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.Annotation')),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
