# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_annotation_annotationcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='geometry_json',
            new_name='cargo_json',
        ),
    ]
