# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20171111_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='local_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
