# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_annotation_local_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='local_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
