# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20180103_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='ordering',
            field=models.IntegerField(blank=True, default=1024, null=True, verbose_name='default ordering'),
        ),
        migrations.AddField(
            model_name='document',
            name='ordering',
            field=models.IntegerField(blank=True, default=1024, null=True, verbose_name='default ordering'),
        ),
        migrations.AddField(
            model_name='folder',
            name='ordering',
            field=models.IntegerField(blank=True, default=1024, null=True, verbose_name='default ordering'),
        ),
    ]
