# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemodel',
            name='name',
            field=models.IntegerField(choices=[(1, 'account activation template'), (2, 'password reset template'), (3, 'meeting invitation template'), (4, 'member invitation template'), (5, 'account canceled template'), (6, 'trial is over template'), (7, 'trial is over and account cancel template'), (8, 'paid is over template'), (9, 'trial reminder template'), (10, 'add document template'), (11, 'document updated template'), (12, 'meeting reminder updated template')], editable=False, unique=True, verbose_name='name'),
        ),
    ]
