# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20170410_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('details_link', models.URLField()),
            ],
        ),
    ]
