# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20170615_0445'),
        ('common', '0003_updatenotification'),
    ]

    operations = [
    ]
