# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RsvpResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response', models.PositiveSmallIntegerField(choices=[(0, 'Accept'), (1, 'Decline'), (2, 'Tentative')], default=2, verbose_name='response')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_responses', to='meetings.Meeting', verbose_name='meeting')),
                ('meeting_repetition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_responses', to='meetings.MeetingRepetition', verbose_name='meeting repetition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_responses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='RsvpRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.PositiveSmallIntegerField(choices=[(0, 'Required responses'), (1, 'Required acceptations'), (2, 'Max responses per invitee'), (3, 'Latest response date'), (4, 'Latest response change date')], default=0, verbose_name='rule type')),
                ('rule_parameters', jsonfield.fields.JSONField(default=b'{}')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_rules', to='meetings.Meeting', verbose_name='meeting')),
            ],
        ),
    ]
