# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvpresponse',
            name='accept_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'In Person'), (1, 'By Phone'), (2, 'Other')], default=0),
        ),
        migrations.AddField(
            model_name='rsvpresponse',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
