# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_account_plan'),
        ('profiles', '0005_auto_20170415_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('voter_ip_address', models.GenericIPAddressField()),
                ('yes_no', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('is_anonymous', models.BooleanField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('state', models.IntegerField(choices=[(1, 'Draft'), (2, 'Published')])),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='accounts.Account', verbose_name='account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='profiles.Membership')),
            ],
        ),
        migrations.CreateModel(
            name='VotingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField()),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Voting')),
            ],
            options={
                'ordering': ['ordering', 'created'],
            },
        ),
        migrations.CreateModel(
            name='VotingQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.VotingQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='VotingQuestionCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=1024)),
                ('last_name', models.CharField(max_length=1024)),
                ('bio', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.VotingQuestion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Membership')),
            ],
        ),
        migrations.CreateModel(
            name='VotingVoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('voter_key', models.CharField(db_index=True, max_length=16, unique=True)),
                ('weight', models.IntegerField(default=1)),
                ('first_name', models.CharField(max_length=1024)),
                ('last_name', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=1024)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Membership')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Voting')),
            ],
        ),
        migrations.AddField(
            model_name='voteranswer',
            name='answers',
            field=models.ManyToManyField(to='voting.VotingQuestionAnswer'),
        ),
        migrations.AddField(
            model_name='voteranswer',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.VotingQuestionCandidate'),
        ),
        migrations.AddField(
            model_name='voteranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.VotingQuestion'),
        ),
    ]
