# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20170513_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteranswer',
            name='voter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='voting.VotingVoter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voteranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_answers', to='voting.VotingQuestion'),
        ),
        migrations.AlterField(
            model_name='votingquestion',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='voting.Voting'),
        ),
        migrations.AlterField(
            model_name='votingquestionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='voting.VotingQuestion'),
        ),
        migrations.AlterField(
            model_name='votingquestioncandidate',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting.VotingQuestion'),
        ),
    ]
