# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20170513_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votingquestioncandidate',
            old_name='user',
            new_name='membership',
        ),
    ]
