# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20170514_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votingquestioncandidate',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='votingvoter',
            old_name='user',
            new_name='membership',
        ),
    ]
