# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 13:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20170514_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingvoter',
            name='voting_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voting',
            name='state',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='votingvoter',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voting.Voting'),
        ),
        migrations.AlterField(
            model_name='votingvoter',
            name='weight',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
