# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20170514_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votingvoter',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='votingvoter',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='voting.Voting'),
        ),
    ]
