# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20170521_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votingvoter',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='votingquestioncandidate',
            name='first_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='votingquestioncandidate',
            name='last_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
