# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20170523_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voteranswer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='votingquestionanswer',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='voteranswer',
            name='for_against_abstain',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'For'), (2, 'Against'), (3, 'Abstain')], null=True),
        ),
        migrations.AlterField(
            model_name='voteranswer',
            name='answers',
            field=models.ManyToManyField(blank=True, to='voting.VotingQuestionAnswer'),
        ),
        migrations.AlterField(
            model_name='votingquestion',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Yes/no'), (2, 'Single Select'), (3, 'Multiple Select'), (4, 'Election'), (5, 'For/Against/Abstain')]),
        ),
        migrations.AlterUniqueTogether(
            name='voteranswer',
            unique_together=set([('voter', 'question')]),
        ),
    ]
