# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20170518_0822'),
        ('voting', '0007_auto_20170523_2219'),
    ]

    operations = [
    ]
