# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20170615_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteranswer',
            name='vote_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
