# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20170615_0445'),
        ('voting', '0008_auto_20170615_1014'),
    ]

    operations = [
    ]
