# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Administrator'), (1, 'Board Chair'), (20, 'CEO'), (21, 'Executive Director'), (2, 'Board Member'), (3, 'Executive Assistant'), (4, 'Guest'), (5, 'Vendor'), (6, 'Staff'), (7, 'Consultant')], null=True, verbose_name='role')),
                ('object_id', models.PositiveIntegerField(verbose_name='object id')),
                ('permission', models.CharField(choices=[(b'view', 'View'), (b'add', 'Add'), (b'edit', 'Edit'), (b'delete', 'Delete'), (b'share', 'Share')], max_length=50, verbose_name='permission')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType', verbose_name='content type')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_permissions', to='profiles.Membership', verbose_name='member')),
            ],
            options={
                'ordering': ('content_type', 'object_id', 'role', 'membership', 'permission'),
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(0, 'Administrator'), (1, 'Board Chair'), (20, 'CEO'), (21, 'Executive Director'), (2, 'Board Member'), (3, 'Executive Assistant'), (4, 'Guest'), (5, 'Vendor'), (6, 'Staff'), (7, 'Consultant')], verbose_name='role')),
                ('permission', models.CharField(choices=[(b'view', 'View'), (b'add', 'Add'), (b'edit', 'Edit'), (b'delete', 'Delete'), (b'share', 'Share')], max_length=50, verbose_name='permission')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'ordering': ('role', 'content_type', 'permission'),
            },
        ),
    ]
