# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectpermission',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Board Chair'), (20, 'CEO'), (21, 'Executive Director'), (2, 'Board Member'), (3, 'Executive Assistant'), (4, 'Guest'), (5, 'Vendor'), (6, 'Staff'), (7, 'Consultant')], null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Board Chair'), (20, 'CEO'), (21, 'Executive Director'), (2, 'Board Member'), (3, 'Executive Assistant'), (4, 'Guest'), (5, 'Vendor'), (6, 'Staff'), (7, 'Consultant')], verbose_name='role'),
        ),
    ]
