# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_auto_20170615_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectpermission',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Board Member'), (21, 'Executive Director'), (20, 'CEO'), (1, 'Board Chair'), (6, 'Staff'), (4, 'Guest'), (5, 'Vendor'), (7, 'Consultant'), (3, 'Executive Assistant')], null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Board Member'), (21, 'Executive Director'), (20, 'CEO'), (1, 'Board Chair'), (6, 'Staff'), (4, 'Guest'), (5, 'Vendor'), (7, 'Consultant'), (3, 'Executive Assistant')], verbose_name='role'),
        ),
    ]
