# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
        ('accounts', '0002_account_plan'),
        ('committees', '0002_committee_chairman'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingNextRepetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('start', models.DateTimeField(verbose_name='from')),
                ('end', models.DateTimeField(verbose_name='to')),
                ('location', models.CharField(max_length=250, verbose_name='location')),
                ('description', models.TextField(verbose_name='description')),
                ('is_event', models.BooleanField(default=False, verbose_name='event')),
                ('status', models.SmallIntegerField(default=0, verbose_name='status')),
                ('last_published', models.DateTimeField(blank=True, null=True, verbose_name='last published')),
                ('last_email_sent', models.DateTimeField(blank=True, null=True, verbose_name='last email sent')),
                ('repeat_type', models.SmallIntegerField(blank=True, choices=[(0, 'No repeat'), (1, 'Every day'), (2, 'Every work day'), (3, 'Every week'), (4, 'Every month'), (5, 'Every year')], default=0, verbose_name='repeat type')),
                ('repeat_interval', models.SmallIntegerField(blank=True, default=1, verbose_name='repeat interval')),
                ('repeat_max_count', models.SmallIntegerField(blank=True, null=True, verbose_name='repeat max count')),
                ('repeat_end_date', models.DateField(blank=True, null=True, verbose_name='repeat end date')),
                ('repeat_week_days', models.SmallIntegerField(blank=True, default=0, verbose_name='repeat week days')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.Account', verbose_name='account')),
                ('committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='committees.Committee', verbose_name='committee')),
                ('extra_members', models.ManyToManyField(db_table=b'meetings_meeting_member', to='profiles.Membership')),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(verbose_name='present')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='meetings.Meeting', verbose_name='meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRepetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repetitions', to='meetings.Meeting', verbose_name='meeting')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='meetingrepetition',
            unique_together=set([('meeting', 'date')]),
        ),
    ]
