# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20170606_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarconnection',
            name='calendar_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Calendar'),
        ),
        migrations.AddField(
            model_name='calendarconnection',
            name='checked_add',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calendarconnection',
            name='checked_conflict',
            field=models.BooleanField(default=True),
        ),
    ]
