# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20170608_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarconnection',
            name='calendar_check_list',
            field=models.TextField(blank=True, help_text='Calendar ID list for checking conflicts', null=True, verbose_name='Calendar Check list'),
        ),
    ]
