# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_calendarconnection_calendar_check_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingattendance',
            name='present',
        ),
    ]
