# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_remove_meetingattendance_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingattendance',
            name='present',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Absent'), (1, 'Attended (in person)'), (2, 'Attended (via conference)')], null=True, verbose_name='present'),
        ),
    ]
