# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20180103_0807'),
        ('meetings', '0007_meetingattendance_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='profiles.Membership'),
        ),
    ]
